### ISSUE TITLE
How is the splat projected?

### ISSUE THREAD

**Issue by yokotsumo** [benpurdy/threejs-decals#2]
Could you confirm in parallel of what the splat is projected (normal at the intersection point, vector between camera and intersection point, vector between mouse coordinates and intersection point, etc.)? I would like to use 'vector between mouse coordinates and intersection point'. If it is not the case now, is there an easy way to make it so?

**Comment by benpurdy** [comment]
The decal factory does not impose any particular projection.  The parameters that you pass into the "projectOnMesh" function specify the origin and direction, it's not set to any fixed projection scheme.  If you look at line 184 in the example you will see that I am using the result of a ray cast to call "projectOnMesh" which uses the ray direction as the projection vector, this results in projection from the camera's perspective. However, if you wanted to use some other projection vector you could easily use the surface normal for the face intersected by the ray, or any arbitrary vector desired..
