### ISSUE TITLE
Explanation needed on UVs

### ISSUE THREAD

**Issue by yokotsumo** [benpurdy/threejs-decals#3]
Thanks for your help so far. Maybe a stupid question, but I do not understand the way UVs coordinates are calculated in Decal.js (l. 126). Why is it (pts[n].x + 1) / 2?

**Comment by benpurdy** [comment]
That is needed to convert from the orthographic coordinate space into UV space. The decal geometry is built by "looking" at the target object through an orthographic camera.  The resulting "view" contains all the vertices that should be covered with the decal.  However, in the orthographic view, the x and y coordinates range from -1 to 1, but UV's expect 0 to 1.  So, adding 1 and diving by 2 will translate between the two coordinate spaces.  Hopefully that makes sense.
